# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TribesRevengeance
email: me@fireant.pw
url: https://tribesrevengeance.net
description: >- # this means to ignore newlines until "baseurl:"
  Tribes Vengeance resurrection site. Information, downloads, guides, tutorials and links.
baseurl: "/" # the subpath of your site, e.g. /blog

# downloads_url: "http://downloads.tribesrevengeance.com"
# download_game_url: "http://downloads.tribesrevengeance.com/TribesVengeance.zip" # the base hostname & protocol for your site, e.g. http://example.com
downloads_url: "https://downloads.tribesrevengeance.net" # the base hostname & protocol for your site, e.g. http://example.com
download_game_url: "https://downloads.tribesrevengeance.net/TribesVengeance.zip" # the base hostname & protocol for your site, e.g. http://example.com
stats_url: "http://stats.tribesrevengeance.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jkelin
github_repo: tribesrevengeance
google_analytics: UA-60631405-2

host: 0.0.0.0

minima:
  date_format: "%d. %m. %Y"

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
